import {
  Armchair,
  Bell,
  Bot,
  Calculator,
  CalendarCheck,
  CalendarDays,
  ChartNoAxesColumn,
  Check,
  Crown,
  Gift,
  Globe,
  Handshake,
  Heart,
  Inbox,
  KeyRound,
  LifeBuoy,
  Megaphone,
  MessageCircle,
  NotebookPen,
  Package,
  Percent,
  Printer,
  QrCode,
  Receipt,
  Scissors,
  ShieldCheck,
  Smartphone,
  Store,
  Timer,
  TrendingUp,
  UserRound,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";

/**
 * Nombre (el que guarda src/lib/barber/marketing.ts) → icono de lucide.
 * Un nombre desconocido cae a las tijeras, nunca a un hueco.
 */
const ICONS: Record<string, LucideIcon> = {
  armchair: Armchair,
  bell: Bell,
  bot: Bot,
  calculator: Calculator,
  "calendar-check": CalendarCheck,
  "calendar-days": CalendarDays,
  chart: ChartNoAxesColumn,
  check: Check,
  crown: Crown,
  gift: Gift,
  globe: Globe,
  handshake: Handshake,
  heart: Heart,
  inbox: Inbox,
  "key-round": KeyRound,
  "life-buoy": LifeBuoy,
  megaphone: Megaphone,
  "message-circle": MessageCircle,
  "notebook-pen": NotebookPen,
  package: Package,
  percent: Percent,
  printer: Printer,
  "qr-code": QrCode,
  receipt: Receipt,
  scissors: Scissors,
  "shield-check": ShieldCheck,
  smartphone: Smartphone,
  store: Store,
  timer: Timer,
  "trending-up": TrendingUp,
  "user-round": UserRound,
  users: Users,
  wallet: Wallet,
};

export function LandingIcon({ name, size = 20 }: { name: string; size?: number }) {
  const Icon = ICONS[name] ?? Scissors;
  return <Icon size={size} aria-hidden="true" />;
}
