"use server";
// Implants — generateImplantPassport. Spec §1.15, §9.3.
// Crea o regenera el carnet del implante. Auto-disparado al cierre
// de createProstheticPhase, también disponible para uso manual.

import { prisma } from "@/lib/prisma";
import {
  generateImplantPassportSchema,
  type GenerateImplantPassportInput,
} from "@/lib/validation/implants";
import { IMPLANT_AUDIT_ACTIONS } from "./audit-actions";
import {
  auditImplant,
  getImplantActionContext,
  loadImplantForCtx,
  revalidateImplantPaths,
} from "./_helpers";
import { fail, isFailure, ok, type ActionResult } from "./result";

export async function generateImplantPassport(
  input: GenerateImplantPassportInput,
): Promise<ActionResult<{ id: string; regenerated: boolean }>> {
  const parsed = generateImplantPassportSchema.safeParse(input);
  if (!parsed.success) {
    return fail(parsed.error.errors[0]?.message ?? "Datos inválidos");
  }

  const ctxRes = await getImplantActionContext({ write: false });
  if (isFailure(ctxRes)) return ctxRes;
  const { ctx } = ctxRes.data;

  const implantRes = await loadImplantForCtx({
    ctx,
    implantId: parsed.data.implantId,
  });
  if (isFailure(implantRes)) return implantRes;
  const before = implantRes.data;

  // Verifica que el implante tenga fase protésica (sin ella el carnet
  // no tiene sentido — Spec §1.15 "Auto-generado al finalizar fase
  // protésica").
  const hasProsthetic = await prisma.implantProstheticPhase.findUnique({
    where: { implantId: parsed.data.implantId },
    select: { id: true },
  });
  if (!hasProsthetic) {
    return fail(
      "El implante aún no tiene fase protésica — el carnet se genera al finalizarla",
    );
  }

  try {
    const existing = await prisma.implantPassport.findUnique({
      where: { implantId: parsed.data.implantId },
      select: { id: true },
    });

    let passportId: string;
    let regenerated = false;
    if (existing) {
      const updated = await prisma.implantPassport.update({
        where: { id: existing.id },
        data: {
          regeneratedAt: new Date(),
          patientPhotoFileId:
            parsed.data.patientPhotoFileId ?? undefined,
        },
        select: { id: true },
      });
      passportId = updated.id;
      regenerated = true;
    } else {
      const created = await prisma.implantPassport.create({
        data: {
          implantId: parsed.data.implantId,
          patientPhotoFileId: parsed.data.patientPhotoFileId ?? null,
          createdByUserId: ctx.userId,
        },
        select: { id: true },
      });
      passportId = created.id;
    }

    await auditImplant({
      ctx,
      action: regenerated
        ? IMPLANT_AUDIT_ACTIONS.PASSPORT_REGENERATED
        : IMPLANT_AUDIT_ACTIONS.PASSPORT_GENERATED,
      entityType: "implant.passport",
      entityId: passportId,
      after: { implantId: parsed.data.implantId, autoGenerated: false },
    });

    revalidateImplantPaths({ patientId: before.patientId });
    return ok({ id: passportId, regenerated });
  } catch (e) {
    console.error("[generateImplantPassport]", e);
    return fail("Error al generar carnet");
  }
}
